### ISSUE TITLE
Error 404 - while trying to use contentful export via cli

### ISSUE THREAD

**Issue by mishragaurav1** [contentful/contentful-export#1042]
Facing 404 issue with below error while trying to use contentful export -:

contentful space export --space-id xxxxxxxxxx --environment-id "development" --management-token xxxxxxxxxxxxxx --export-dir Downloads\ContentfulExport --include-drafts false --skip-role true --skip-webhooks true --error-log-file Downloads\ContentfulExport\error-log-file.txt --save-file true

  √ Initialize client (1s)
  > Fetching data from space
    × Connecting to space (1s)
      → NotFound: Status: 404 - Not Found - Message: The resource could not be found. - Request ID: 949df1e3-c549-44da-
9…
      Fetching content types data
      Fetching tags data
      Fetching editor interfaces data
      Fetching content entries data
      Fetching assets data
      Fetching locales data
      Fetching webhooks data
      Fetching roles data
    Download assets
    Write export log file

The following 0 errors and 0 warnings occurred:

19:05:09 - Error: Status: 404 - Not Found - Message: The resource could not be found. - Request ID: 949df1e3-c549-44da-9e86-531e70e61057

Stored the detailed error log file at:
Downloads\ContentfulExport\error-log-file.txt
  Error: Errors occured
┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐│ ContentfulMultiError: Errors occured                                                                                 ││     at C:\snapshot\project\node_modules\contentful-export\dist\index.js:190:28                                       ││     at tryCatcher (C:\snapshot\project\node_modules\bluebird\js\release\util.js:16:23)                               ││     at Promise._settlePromiseFromHandler (C:\snapshot\project\node_modules\bluebird\js\release\promise.js:547:31)    ││     at Promise._settlePromise (C:\snapshot\project\node_modules\bluebird\js\release\promise.js:604:18)               ││     at Promise._settlePromise0 (C:\snapshot\project\node_modules\bluebird\js\release\promise.js:649:10)              ││     at Promise._settlePromises (C:\snapshot\project\node_modules\bluebird\js\release\promise.js:729:18)              ││     at _drainQueueStep (C:\snapshot\project\node_modules\bluebird\js\release\async.js:93:12)                         ││     at _drainQueue (C:\snapshot\project\node_modules\bluebird\js\release\async.js:86:9)                              ││     at Async._drainQueues (C:\snapshot\project\node_modules\bluebird\js\release\async.js:102:5)                      ││     at Immediate._onImmediate (C:\snapshot\project\node_modules\bluebird\js\release\async.js:15:14)                  ││     at processImmediate (internal/timers.js:461:21)                                                                  │└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

**Comment by marcolink** [comment]
Closing due to inactivity
