### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by rngadam** [contentful/contentful-export#13]
```
> npm install -g contentful-export
/usr/local/bin/contentful-export -> /usr/local/lib/node_modules/contentful-export/bin/contentful-export
/usr/local/lib
└─┬ contentful-export@1.3.1 
  ├── bluebird@3.4.6 
  ├─┬ contentful-batch-libs@4.3.0 
  │ ├─┬ babel-runtime@6.18.0 
  │ │ ├── core-js@2.4.1 
  │ │ └── regenerator-runtime@0.9.5 
  │ ├─┬ contentful@3.7.0 
  │ │ └─┬ contentful-sdk-core@2.3.4 
  │ │   ├─┬ follow-redirects@0.0.7 
  │ │   │ ├─┬ debug@2.2.0 
  │ │   │ │ └── ms@0.7.1 
  │ │   │ └── stream-consume@0.1.0 
  │ │   └── qs@6.3.0 
  │ ├── contentful-management@1.2.1 
  │ └─┬ npmlog@2.0.4 
  │   ├── ansi@0.3.1 
  │   └─┬ gauge@1.2.7 
     ├── lodash.pad@4.5.1 
  │     ├── lodash.padend@4.6.1 
  │     └── lodash.padstart@4.6.1 
  ├─┬ fs-extra@0.30.0 
  │ ├── graceful-fs@4.1.10 
  │ ├── jsonfile@2.4.0 
  │ ├── klaw@1.3.1 
  │ ├── path-is-absolute@1.0.1 
  │ └─┬ rimraf@2.5.4 
  │   └─┬ glob@7.1.1 
  │     ├── fs.realpath@1.0.0 
  │     ├─┬ inflight@1.0.6 
  │     │ └── wrappy@1.0.2 
  │     ├── inherits@2.0.3 
  │     ├─┬ minimatch@3.0.3 
  │     │ └─┬ brace-expansion@1.1.6 
  │     │   ├── balanced-match@0.4.2 
  │     │   └── concat-map@0.0.1 
  │     └── once@1.4.0 
  ├── json-stringify-safe@5.0.1 
  ├── lodash@4.16.6 
  ├─┬ npmlog@4.0.0 
  │ ├─┬ are-we-there-yet@1.1.2 
  │ │ ├── delegates@1.0.0 
  │ │ └─┬ readable-stream@2.1.5 
  │ │   ├── buffer-shims@1.0.0 
  │ │   ├── core-util-is@1.0.2 
  │ │   ├── isarray@1.0.0 
  │ │   ├── process-nextick-args@1.0.7 
  │ │   ├── string_decoder@0.10.31 
  │ │   └── util-deprecate@1.0.2 
  │ ├── console-control-strings@1.1.0 
  │ ├─┬ gauge@2.6.0 
  │ │ ├── aproba@1.0.4 
  │ │ ├── has-color@0.1.7 
  │ │ ├── has-unicode@2.0.1 
  │ │ ├── object-assign@4.1.0 
  │ │ ├── signal-exit@3.0.1 
  │ │ ├─┬ strip-ansi@3.0.1 
  │ │ │ └── ansi-regex@2.0.0 
  │ │ └── wide-align@1.1.0 
  │ └── set-blocking@2.0.0 
  └─┬ yargs@5.0.0 
    ├─┬ cliui@3.2.0 
    │ └── wrap-ansi@2.0.0 
    ├── decamelize@1.2.0 
    ├── get-caller-file@1.0.2 
    ├── lodash.assign@4.2.0 
    ├─┬ os-locale@1.4.0 
    │ └─┬ lcid@1.0.0 
    │   └── invert-kv@1.0.0 
    ├─┬ read-pkg-up@1.0.1 
    │ ├─┬ find-up@1.1.2 
    │ │ ├── path-exists@2.1.0 
    │ │ └─┬ pinkie-promise@2.0.1 
    │ │   └── pinkie@2.0.4 
    │ └─┬ read-pkg@1.1.0 
    │   ├─┬ load-json-file@1.1.0 
    │   │ ├─┬ parse-json@2.2.0 
    │   │ │ └─┬ error-ex@1.3.0 
    │   │ │   └── is-arrayish@0.2.1 
    │   │ ├── pify@2.3.0 
    │   │ └─┬ strip-bom@2.0.0 
    │   │   └── is-utf8@0.2.1 
    │   ├─┬ normalize-package-data@2.3.5 
    │   │ ├── hosted-git-info@2.1.5 
    │   │ ├─┬ is-builtin-module@1.0.0 
    │   │ │ └── builtin-modules@1.1.1 
    │   │ ├── semver@5.3.0 
    │   │ └─┬ validate-npm-package-license@3.0.1 
    │   │   ├─┬ spdx-correct@1.0.2 
    │   │   │ └── spdx-license-ids@1.2.2 
    │   │   └── spdx-expression-parse@1.0.4 
    │   └── path-type@1.1.0 
    ├── require-directory@2.1.1 
    ├── require-main-filename@1.0.1 
    ├─┬ string-width@1.0.2 
    │ ├── code-point-at@1.1.0 
    │ └─┬ is-fullwidth-code-point@1.0.0 
    │   └── number-is-nan@1.0.1 
    ├── which-module@1.0.0 
    ├── window-size@0.2.0 
    ├── y18n@3.2.1 
    └─┬ yargs-parser@3.2.0 
      └── camelcase@3.0.0 
```

fails:

```
module.js:442
    throw err;
    ^

Error: Cannot find module 'babel-register'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/contentful-export/index.js:5:5)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

workaround:

```
npm install -g babel-register
```
then fails:

```
module.js:442
    throw err;
    ^

Error: Cannot find module './lib/run-contentful-export'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/contentful-export/index.js:6:22)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

Not sure what's going on here. The repo seems to have dist/run-contentful-export.js.

**Comment by Khaledgarbaya** [comment]
@rngadam, I think I just fixed that here https://github.com/contentful/contentful-export/issues/12 today can you try to install again ?

**Comment by rngadam** [comment]
Indeed, it's fixed in the repo:

```
git clone git@github.com:contentful/contentful-export.git
cd contentful-export/
npm install
npm run build 
npm link
```

...and then:

```
> contentful-export --space-id SPACE_ID --management-token MANAGEMENT_TOKEN --export-dir EXPORT_DIR
info Contentful Export Tool:
Fetching Space data ... 
info Getting content from source space 
```
