### ISSUE TITLE
Invalid JSON while importing content

### ISSUE THREAD

**Issue by iahujaklick** [contentful/contentful-export#1312]
While importing content "Invalid JSON" is coming up. Please help! 

```
/usr/local/lib/node_modules/contentful-cli/dist/lib/cli.js:32
        throw err;
        ^
YError: Invalid JSON config file: true
    at Object.runValidation [as _runValidation] (/usr/local/lib/node_modules/contentful-cli/node_modules/yargs/yargs.js:1179:28)
    at Object.runCommand (/usr/local/lib/node_modules/contentful-cli/node_modules/yargs/lib/command.js:233:36)
    at Object.parseArgs [as _parseArgs] (/usr/local/lib/node_modules/contentful-cli/node_modules/yargs/yargs.js:1087:30)
    at Object.runCommand (/usr/local/lib/node_modules/contentful-cli/node_modules/yargs/lib/command.js:200:45)
    at Object.parseArgs [as _parseArgs] (/usr/local/lib/node_modules/contentful-cli/node_modules/yargs/yargs.js:1087:30)
    at Object.parse (/usr/local/lib/node_modules/contentful-cli/node_modules/yargs/yargs.js:575:25)
    at Object.<anonymous> (/usr/local/lib/node_modules/contentful-cli/dist/lib/cli.js:37:6)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/contentful-cli/bin/contentful.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)

```

Command I use "contentful space import --config  --content-file /Users/myuser/Downloads/contentful-export-pbsbtribdlpc-master-2023-03-09T15-51-59.json"

**Comment by skumarklick** [comment]
You need to create JSON with the described format here:- https://www.contentful.com/developers/docs/tutorials/cli/import-and-export/

**Comment by iahujaklick** [comment]
Thanks @skumarklick!
