### ISSUE TITLE
Can't get contentful-export to run

### ISSUE THREAD

**Issue by matt-hammond** [contentful/contentful-export#19]
With a vanilla node install, following the steps:

**sudo npm install -g contentful-export**

then:

**contentful-export**

I get the following response:

_$ contentful-export
module.js:471
    throw err;
    ^

Error: Cannot find module 'babel-register'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/contentful-export/index.js:5:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at require (internal/module.js:20:19)_

If I then do a global install of babel-register and re-run, I then get:

_$ contentful-export
module.js:471
    throw err;
    ^

Error: Cannot find module './lib/run-contentful-export'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/contentful-export/index.js:6:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at require (internal/module.js:20:19)_

**Comment by Khaledgarbaya** [comment]
@matt-hammond ,
I just desicovered that a dependency was removed from the package.json in one of the recent merges, Sorry about that.
I push a fix and a new npm version should be available in the next few minutes.
