### ISSUE TITLE
Export fails on 404 error

### ISSUE THREAD

**Issue by apaatsio** [contentful/contentful-export#23]
Export fails every time on a 404 error. It varies on what resource it fails on. I have experienced at least roles, locales, and webhook_definitions returning 404.

I have double checked that the space id is correct.

```
❯ contentful-export --config export-config.json 
info Contentful Export Tool:
Fetching Space data ... 
info Getting content from source space 
ERR! Failed with
 NotFound: {
ERR! Failed with
   "request": {
ERR! Failed with
     "url": "https://api.contentful.com:443/spaces/XXX/locales",
ERR! Failed with
     "headers": {
ERR! Failed with
       "Accept": "application/json, text/plain, */*",
ERR! Failed with
       "Content-Type": "application/vnd.contentful.management.v1+json",
ERR! Failed with
       "X-Contentful-User-Agent": "contentful-management.js/1.3.0",
ERR! Failed with
       "Authorization": "Bearer YYY",
ERR! Failed with
       "user-agent": "node.js/v6.5.0",
ERR! Failed with
       "Accept-Encoding": "gzip"
ERR! Failed with
     },
ERR! Failed with
     "method": "get"
ERR! Failed with
   },
ERR! Failed with
   "status": 404,
ERR! Failed with
   "statusText": "Not Found",
ERR! Failed with
   "requestId": "ea8efc9e7829d7f1c6d04c9c84faad4c",
ERR! Failed with
   "message": "The resource could not be found."
ERR! Failed with
 }
ERR! Failed with
     at errorHandler (/path/to/node_modules/contentful-management/dist/error-handler.js:67:15)
ERR! Failed with
     at process._tickCallback (internal/process/next_tick.js:103:7)
ERR! Failed with
  { NotFound: {
ERR! Failed with
   "request": {
ERR! Failed with
     "url": "https://api.contentful.com:443/spaces/XXX/locales",
ERR! Failed with
     "headers": {
ERR! Failed with
       "Accept": "application/json, text/plain, */*",
ERR! Failed with
       "Content-Type": "application/vnd.contentful.management.v1+json",
ERR! Failed with
       "X-Contentful-User-Agent": "contentful-management.js/1.3.0",
ERR! Failed with
       "Authorization": "Bearer YYY",
ERR! Failed with
       "user-agent": "node.js/v6.5.0",
ERR! Failed with
       "Accept-Encoding": "gzip"
ERR! Failed with
     },
ERR! Failed with
     "method": "get"
ERR! Failed with
   },
ERR! Failed with
   "status": 404,
ERR! Failed with
   "statusText": "Not Found",
ERR! Failed with
   "requestId": "ea8efc9e7829d7f1c6d04c9c84faad4c",
ERR! Failed with
   "message": "The resource could not be found."
ERR! Failed with
 }
ERR! Failed with
     at errorHandler (/path/to/node_modules/contentful-management/dist/error-handler.js:67:15)
ERR! Failed with
     at process._tickCallback (internal/process/next_tick.js:103:7)
ERR! Failed with
   name: 'NotFound',
ERR! Failed with
   message: '{\n  "request": {\n    "url": "https://api.contentful.com:443/spaces/XXX/locales",\n    "headers": {\n      "Accept": "application/json, text/plain, */*",\n      "Content-Type": "application/vnd.contentful.management.v1+json",\n      "X-Contentful-User-Agent": "contentful-management.js/1.3.0",\n      "Authorization": "Bearer YYY",\n      "user-agent": "node.js/v6.5.0",\n      "Accept-Encoding": "gzip"\n    },\n    "method": "get"\n  },\n  "status": 404,\n  "statusText": "Not Found",\n  "requestId": "ea8efc9e7829d7f1c6d04c9c84faad4c",\n  "message": "The resource could not be found."\n}' }
```

Config
```json
{
  "spaceId": "XXX",
  "managementToken": "YYY",
  "previewToken": "ZZZ",
  "exportDir": "/tmp/contentful-export",
  "includeDrafts": "true",
  "downloadAssets": "true"
}
```

Edit: I noticed that in my config the includeDrafts and downloadAssets are strings when they probably should be boolean, but that doesn't affect the end result. In both cases I'm getting the 404.

**Comment by apaatsio** [comment]
In the browser the same request is working fine when I go to https://app.contentful.com/spaces/XXX/settings/locales

**Comment by Khaledgarbaya** [comment]
hi @apaatsio ,
I think the draft export is kinda broken. I will look into it asap.
Best,
Khaled

**Comment by apaatsio** [comment]
Seems so. I changed the config to have `"includeDrafts": false,` and now I get an error:

```
❯ contentful-export --config export-config.json 
ERR! Please make sure to specify --include-drafts to be able to get drafts 
```

**Comment by apaatsio** [comment]
Still getting a similar error when testing with the branch @ #24 

```
❯ node --version
v4.6.2
❯ npm --version
2.15.11
❯ uname -a 
Linux a1 4.8.14-1-MANJARO #1 SMP PREEMPT Sat Dec 10 23:58:26 UTC 2016 x86_64 GNU/Linux
❯ git log -n 1
commit 32e64d83f34fd85936059010c54b9cd6ef8b5cb7
Author: Khaledgarbaya <khaledgarbaya@gmail.com>
Date:   Wed Dec 21 13:07:41 2016 +0100

    add placeholder version
❯ npm install
# removed some lines here
❯ npm run build

> contentful-export@0.0.0-placeholder build /home/antti/projects/contentful-export
> npm run clean && mkdirp dist && babel lib --out-dir dist


> contentful-export@0.0.0-placeholder clean /home/antti/projects/contentful-export
> rimraf dist

lib/download-asset.js -> dist/download-asset.js
lib/dump-error-buffer.js -> dist/dump-error-buffer.js
lib/run-contentful-export.js -> dist/run-contentful-export.js
lib/usageParams.js -> dist/usageParams.js
❯ ./bin/contentful-export --config /path/to/export-config.json 
info Contentful Export Tool:
Fetching Space data ... 
info Getting content from source space 
ERR! Failed with
 NotFound: {
ERR! Failed with
   "request": {
ERR! Failed with
     "url": "https://api.contentful.com:443/spaces/XXX/webhook_definitions",
ERR! Failed with
     "headers": {
ERR! Failed with
       "Accept": "application/json, text/plain, */*",
ERR! Failed with
       "Content-Type": "application/vnd.contentful.management.v1+json",
ERR! Failed with
       "X-Contentful-User-Agent": "contentful-management.js/1.3.0",
ERR! Failed with
       "Authorization": "Bearer YYY",
ERR! Failed with
       "user-agent": "node.js/v4.6.2",
ERR! Failed with
       "Accept-Encoding": "gzip"
ERR! Failed with
     },
ERR! Failed with
     "method": "get"
ERR! Failed with
   },
ERR! Failed with
   "status": 404,
ERR! Failed with
   "statusText": "Not Found",
ERR! Failed with
   "requestId": "0f6eb49c1deda250bffb5e13c66be4ad",
ERR! Failed with
   "message": "The resource could not be found."
ERR! Failed with
 }
ERR! Failed with
     at errorHandler (/home/antti/projects/contentful-export/node_modules/contentful-batch-libs/node_modules/contentful-management/dist/error-handler.js:67:15)
ERR! Failed with
     at run (/home/antti/projects/contentful-export/node_modules/contentful-batch-libs/node_modules/contentful-management/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:87:22)
ERR! Failed with
     at /home/antti/projects/contentful-export/node_modules/contentful-batch-libs/node_modules/contentful-management/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:100:28
ERR! Failed with
     at flush (/home/antti/projects/contentful-export/node_modules/contentful-batch-libs/node_modules/contentful-management/node_modules/babel-runtime/node_modules/core-js/library/modules/_microtask.js:18:9)
ERR! Failed with
     at nextTickCallbackWith0Args (node.js:436:9)
ERR! Failed with
     at process._tickCallback (node.js:365:13)
ERR! Failed with
  { [NotFound: {
ERR! Failed with
   "request": {
ERR! Failed with
     "url": "https://api.contentful.com:443/spaces/XXX/webhook_definitions",
ERR! Failed with
     "headers": {
ERR! Failed with
       "Accept": "application/json, text/plain, */*",
ERR! Failed with
       "Content-Type": "application/vnd.contentful.management.v1+json",
ERR! Failed with
       "X-Contentful-User-Agent": "contentful-management.js/1.3.0",
ERR! Failed with
       "Authorization": "Bearer YYY",
ERR! Failed with
       "user-agent": "node.js/v4.6.2",
ERR! Failed with
       "Accept-Encoding": "gzip"
ERR! Failed with
     },
ERR! Failed with
     "method": "get"
ERR! Failed with
   },
ERR! Failed with
   "status": 404,
ERR! Failed with
   "statusText": "Not Found",
ERR! Failed with
   "requestId": "0f6eb49c1deda250bffb5e13c66be4ad",
ERR! Failed with
   "message": "The resource could not be found."
ERR! Failed with
 }]
ERR! Failed with
   name: 'NotFound',
ERR! Failed with
   message: '{\n  "request": {\n    "url": "https://api.contentful.com:443/spaces/XXX/webhook_definitions",\n    "headers": {\n      "Accept": "application/json, text/plain, */*",\n      "Content-Type": "application/vnd.contentful.management.v1+json",\n      "X-Contentful-User-Agent": "contentful-management.js/1.3.0",\n      "Authorization": "Bearer YYY",\n      "user-agent": "node.js/v4.6.2",\n      "Accept-Encoding": "gzip"\n    },\n    "method": "get"\n  },\n  "status": 404,\n  "statusText": "Not Found",\n  "requestId": "0f6eb49c1deda250bffb5e13c66be4ad",\n  "message": "The resource could not be found."\n}' }
```

**Comment by apaatsio** [comment]
I tried the export with another space and **it worked**! So for some reason it's now working with this one particular space.

**Comment by apaatsio** [comment]
The non-working space has a lot of assets/images. Could those be the culprit?

**Comment by Khaledgarbaya** [comment]
@apaatsio think it is related to the token, maybe you don't have access to webhooks

**Comment by apaatsio** [comment]
Yes! I made the user who owned the token an admin of that space and it started working! Thanks!

The error message should be 401 and not 404. It was a bit misleading.
