### ISSUE TITLE
Package does not work as a library

### ISSUE THREAD

**Issue by eisenbergrobin** [contentful/contentful-export#3]
Steps to reproduce the problem: 

- ```npm init``` a project on node 4.3.2
- `npm i --save-dev contentful-export`
```
contentful-export@1.0.4 node_modules/contentful-export
├── json-stringify-safe@5.0.1
├── bluebird@3.4.1
├── npmlog@2.0.4 (ansi@0.3.1, gauge@1.2.7, are-we-there-yet@1.1.2)
├── yargs@4.8.1 (decamelize@1.2.0, y18n@3.2.1, lodash.assign@4.1.0, which-module@1.0.0, set-blocking@2.0.0, require-main-filename@1.0.1, window-size@0.2.0, require-directory@2.1.1, get-caller-file@1.0.1, yargs-parser@2.4.1, os-locale@1.4.0, cliui@3.2.0, string-width@1.0.1, read-pkg-up@1.0.1)
├── lodash@4.14.0
└── contentful-batch-libs@4.0.13 (contentful-management@1.1.9, contentful@3.5.0, babel-runtime@6.11.6) 
```

Then run the following code: 

```
const spaceExport = require('contentful-export')

const options = {
  spaceId: 'a_valid_space_id',
  managementToken: 'a_valid_mgmnt_token',
};

spaceExport(options)
  .then((output) => {
    console.log('space data', output)
  })
  .catch((err) => {
    console.log('oh no! errors occurred!', err)
  })

```

Throws the following error: 

```
/exporter/node_modules/contentful-export/node_modules/contentful-batch-libs/utils/create-clients.js:34
    spaceId: opts.sourceSpace
                 ^

TypeError: Cannot read property 'sourceSpace' of undefined
    at createClients (exporter/node_modules/contentful-export/node_modules/contentful-batch-libs/utils/create-clients.js:34:18)
    at runContentfulExport (exporter/node_modules/contentful-export/dist/run-contentful-export.js:41:45)
    at Object.<anonymous> (exporter/index.js:9:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
    at node.js:962:3

```

Using the same SPACE_ID and MANAGEMENT_TOKEN in the CLI works correctly.

My use case is I'd like to create automatic backup AWS Lambdas to backup my Contentful spaces, and the CLI tool is not an option in this context.

**Comment by Khaledgarbaya** [comment]
hi @eisenbergrobin 
let me take a look and get back to you asap

**Comment by Khaledgarbaya** [comment]
sorry I closed the issue by mistake

**Comment by Khaledgarbaya** [comment]
yeah it was a bug Sorry about that I just fixed it and should be working in the next version which will be released as soon as the ci build finishes

**Comment by Khaledgarbaya** [comment]
hey @eisenbergrobin 
the fix should be in **v1.0.5**

**Comment by eisenbergrobin** [comment]
@Khaledgarbaya 

I can confirm this is fixed. Thanks for the quick fix :)

**Comment by Khaledgarbaya** [comment]
![](https://media.giphy.com/media/CHSC7ASSCZWEM/giphy.gif)
