### ISSUE TITLE
Export fails on 404 error

### ISSUE THREAD

**Issue by SalilGavhankar** [contentful/contentful-export#33]
I tried to export the space with command
contentful-export --space-id=xxx --management-token=xxx

I have Administrator role for the source space.

Its giving following error 
ERR! Failed with
 NotFound: {
ERR! Failed with
   "request": {
ERR! Failed with
     "url": "https://api.contentful.com:443/spaces/xxx",
ERR! Failed with
     "headers": {
ERR! Failed with
       "Accept": "application/json, text/plain, */*",
ERR! Failed with
       "Content-Type": "application/vnd.contentful.management.v1+json",
ERR! Failed with
       "X-Contentful-User-Agent": "contentful-management.js/1.3.1",
ERR! Failed with
       "Authorization": "Bearer xyyy",
ERR! Failed with
       "user-agent": "node.js/v5.10.1",
ERR! Failed with
       "Accept-Encoding": "gzip"
ERR! Failed with
     },
ERR! Failed with
     "method": "get"
ERR! Failed with
   },
ERR! Failed with
   "status": 404,
ERR! Failed with
   "statusText": "Not Found",
ERR! Failed with
   "requestId": "1e005f504a5eeb9fa2e9c7653248f2d4",
ERR! Failed with
   "message": "The resource could not be found."
ERR! Failed with
 }
ERR! Failed with
     at errorHandler (/path/to/node_modules\contentful-export\no
de_modules\contentful-management\dist\error-handler.js:65:15)
ERR! Failed with
     at run (/path/to/node_modules\contentful-export\node_module
s\core-js\library\modules\es6.promise.js:87:22)
ERR! Failed with
     at /path/to/node_modules\contentful-export\node_modules\cor
e-js\library\modules\es6.promise.js:100:28
ERR! Failed with
     at flush (/path/to/node_modules\node_modules\contentful-export\node_modu
les\core-js\library\modules\_microtask.js:18:9)
ERR! Failed with
     at _combinedTickCallback (internal/process/next_tick.js:67:7)
ERR! Failed with
     at process._tickCallback (internal/process/next_tick.js:98:9)
ERR! Failed with
  { [NotFound: {
ERR! Failed with
   "request": {
ERR! Failed with
     "url": "https://api.contentful.com:443/spaces/62i11p9ten5u",
ERR! Failed with
     "headers": {
ERR! Failed with
       "Accept": "application/json, text/plain, */*",
ERR! Failed with
       "Content-Type": "application/vnd.contentful.management.v1+json",
ERR! Failed with
       "X-Contentful-User-Agent": "contentful-management.js/1.3.1",
ERR! Failed with
       "Authorization": "Bearer xyxy",
ERR! Failed with
       "user-agent": "node.js/v5.10.1",
ERR! Failed with
       "Accept-Encoding": "gzip"
ERR! Failed with
     },
ERR! Failed with
     "method": "get"
ERR! Failed with
   },
ERR! Failed with
   "status": 404,
ERR! Failed with
   "statusText": "Not Found",
ERR! Failed with
   "requestId": "1e005f504a5eeb9fa2e9c7653248f2d4",
ERR! Failed with
   "message": "The resource could not be found."
ERR! Failed with
 }]
ERR! Failed with
   name: 'NotFound',
ERR! Failed with
   message: '{\n  "request": {\n    "url": "https://api.contentful.com:443/spaces/xxx",\n
  "headers": {\n      "Accept": "application/json, text/plain, */*",\n      "Content-Type": "applica
tion/vnd.contentful.management.v1+json",\n      "X-Contentful-User-Agent": "contentful-management.js
/1.3.1",\n      "Authorization": "Bearer xyx",\n      "user-agent": "node.js/v5.10.1",\n      "Accept-Encoding": "gzip"\n    },\n    "metho
d": "get"\n  },\n  "status": 404,\n  "statusText": "Not Found",\n  "requestId": "1e005f504a5eeb9fa2e
9c7653248f2d4",\n  "message": "The resource could not be found."\n}' }

Kindly request for help.

**Comment by SalilGavhankar** [comment]
The issue was because of incorrect management token. After correcting the token, space contents got exported.

Hence closing the issue.
